name: build

on: [push, pull_request]

jobs:
  phpunit:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: yiitest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, sqlite, pdo_sqlite, pdo_mysql, memcached
          tools: composer:v2
          coverage: none

      - name: Install Memcached.
        uses: niden/actions-memcached@v7

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
      - name: Run unit tests
        run: vendor/bin/phpunit --colors=always
